library(tidyverse)
library(shiny)
library(bslib)
library(janitor)
library(reactable)
library(shinyjs)
library(glue)
library(readxl)
library(yaml)

# set output options
shiny::devmode(devmode = TRUE)
options(bslib.color_contrast_warnings = FALSE)
options(bslib.precompiled = TRUE)
options(sass.cache = TRUE)
options(shiny.minified = TRUE)
